In [1]:
!pip install nltk

In [2]:
import nltk
from nltk import word_tokenize
nltk.download('punkt')
from nltk.tokenize import word_tokenize  
print(word_tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))  

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\a0109\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [3]:
!pip install kss

  Created wheel for kss: filename=kss-3.5.6-py3-none-any.whl size=42448525 sha256=e14917174b825ff481a3363da4a2722af7248673cc164fdf3e40e71d974807f0
  Stored in directory: c:\users\a0109\appdata\local\pip\cache\wheels\6d\cc\82\676f4ad835320fae7e5ad474769a1f06fceb413c8ba391fb49
Successfully built kss


In [4]:
import re
r=re.compile("a.c")
r.search("kkk")
r.search("abc")

<re.Match object; span=(0, 3), match='abc'>

In [5]:
r=re.compile("ab?c")
r.search("abbc")
r.search("abc")

<re.Match object; span=(0, 3), match='abc'>

In [6]:
r.search("ac")

<re.Match object; span=(0, 2), match='ac'>

In [7]:
r=re.compile("ab*c")
r.search("a")

In [8]:
r.search("ac")

<re.Match object; span=(0, 2), match='ac'>

In [9]:
r.search("abc")

<re.Match object; span=(0, 3), match='abc'>

In [13]:
r.search("aabbbc")

<re.Match object; span=(1, 6), match='abbbc'>

In [14]:
r=re.compile("ab+c")
r.search("ac")
r.search("abc")

<re.Match object; span=(0, 3), match='abc'>

In [15]:
r=re.compile("^a")
r.search("bbc")
r.search("ab")

<re.Match object; span=(0, 1), match='a'>

In [16]:
r=re.compile("ab{2}c")
r.search("ac")
r.search("abc")
r.search("abbc")

<re.Match object; span=(0, 4), match='abbc'>

In [17]:
r.search("abbbbbc")

In [18]:
text="Regular:"
re.sub("[^a-zA-Z]",'',text)

'Regular'

In [21]:
import nltk
from nltk.tokenize import RegexpTokenizer
tokenizer = RegexpTokenizer("[\w]+")
print(tokenizer.tokenize("Don't be fooled by"))

['Don', 't', 'be', 'fooled', 'by']


In [26]:
tokenizer=RegexpTokenizer('[\s]+', gaps=True)
print(tokenizer.tokenize("Don't be fooled by"))

["Don't", 'be', 'fooled', 'by']


In [27]:
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [28]:
text ="A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

In [29]:
text = sent_tokenize(text)
print(text)

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']


In [38]:
import nltk
nltk.download('stopwords')

vocab = {}
sentences=[]
stop_words=set(stopwords.words('english'))

for i in text:
    sentence = word_tokenize(i)
    result=[]
    
    for word in sentence:
        word=word.lower()
        if word not in stop_words:
            if len(word) >2:
                result.append(word)
                if word not in vocab:
                    vocab[word] = 0
                else:
                    vocab[word] += 1
    sentences.append(result)
print(sentences)
print(vocab)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]
{'barber': 7, 'person': 2, 'good': 0, 'huge': 4, 'knew': 0, 'secret': 5, 'kept': 3, 'word': 1, 'keeping': 1, 'driving': 0, 'crazy': 0, 'went': 0, 'mountain': 0}


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\a0109\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


## 20220905

In [2]:
!pip install spacy

  Attempting uninstall: smart-open
    Found existing installation: smart-open 5.1.0
    Uninstalling smart-open-5.1.0:
      Successfully uninstalled smart-open-5.1.0


In [3]:
!pip show spacy

Name: spacy
Version: 3.4.1
Summary: Industrial-strength Natural Language Processing (NLP) in Python
Home-page: https://spacy.io
Author: Explosion
Author-email: contact@explosion.ai
License: MIT
Location: c:\users\a0109\anaconda3\lib\site-packages
Requires: langcodes, catalogue, setuptools, spacy-loggers, typer, preshed, numpy, spacy-legacy, srsly, packaging, cymem, pydantic, thinc, wasabi, requests, pathy, jinja2, tqdm, murmurhash
Required-by: 


In [4]:
!python -m spacy download en_core_web_sm

[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


In [5]:
import spacy
spacy_en=spacy.load('en_core_web_sm')
text='David\'s book wasn\'t famous, but his family loved his book.'
for token in spacy_en.tokenizer(text):
    print(token)

David
's
book
was
n't
famous
,
but
his
family
loved
his
book
.


In [6]:
for token in spacy_en.tokenizer(text):
    print(f"token:{token.text}, PoS:{token.pos_}, lemman: {token.lemma_}")

token:David, PoS:, lemman: 
token:'s, PoS:, lemman: 
token:book, PoS:, lemman: 
token:was, PoS:, lemman: 
token:n't, PoS:, lemman: 
token:famous, PoS:, lemman: 
token:,, PoS:, lemman: 
token:but, PoS:, lemman: 
token:his, PoS:, lemman: 
token:family, PoS:, lemman: 
token:loved, PoS:, lemman: 
token:his, PoS:, lemman: 
token:book, PoS:, lemman: 
token:., PoS:, lemman: 


In [9]:
stop_words=spacy.lang.en.stop_words.STOP_WORDS

for i, stop_word in enumerate(stop_words):
    if i == 10: break
    print(stop_word)

see
when
not
at
namely
formerly
him
this
whereafter
from


In [10]:
!pip install nltk

In [11]:
!pip show nltk

Name: nltk
Version: 3.7
Summary: Natural Language Toolkit
Home-page: https://www.nltk.org/
Author: NLTK Team
Author-email: nltk.team@gmail.com
License: Apache License, Version 2.0
Location: c:\users\a0109\anaconda3\lib\site-packages
Requires: click, regex, tqdm, joblib
Required-by: 


In [12]:
import nltk
nltk.download('popular')

[nltk_data] Downloading collection 'popular'
[nltk_data]    | 
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     C:\Users\a0109\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\cmudict.zip.
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     C:\Users\a0109\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\gazetteers.zip.
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     C:\Users\a0109\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\genesis.zip.
[nltk_data]    | Downloading package gutenberg to
[nltk_data]    |     C:\Users\a0109\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\gutenberg.zip.
[nltk_data]    | Downloading package inaugural to
[nltk_data]    |     C:\Users\a0109\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\inaugural.zip.
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     C:\Users\a0109\AppData\Roaming\nl

True

In [13]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
print(word_tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))

['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\a0109\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [15]:
from nltk.tokenize import word_tokenize
text='David\'s book wasn\'t famous, but his family loved his book.'
word_tokenize(text)

['David',
 "'s",
 'book',
 'was',
 "n't",
 'famous',
 ',',
 'but',
 'his',
 'family',
 'loved',
 'his',
 'book',
 '.']

In [16]:
from nltk import word_tokenize

sentence="The Matrix is everywhere its all around us, here even in this room."
words=word_tokenize(sentence)
print(type(words), len(words))
print(words)

<class 'list'> 15
['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.']


## N-gram

In [22]:
from nltk import ngrams
sentence="there is no royal road to learning"
bigram=list(ngrams(sentence.split(), 3))
print(bigram)

[('there', 'is', 'no'), ('is', 'no', 'royal'), ('no', 'royal', 'road'), ('royal', 'road', 'to'), ('road', 'to', 'learning')]


In [19]:
trigram=list(ngrams(sentence.split(),3))
print(trigram)

[('there', 'is', 'no'), ('is', 'no', 'royal'), ('no', 'royal', 'road'), ('royal', 'road', 'to'), ('road', 'to', 'learning')]


In [21]:
def n_grams(text,n):
    '''
    takes tokens or text, returns a list of n-grams
    '''
    return [text[i:i+n] for i in range(len(text)-n+1)]
cleaned=["mary",",","n't","slap","green","witch","."]
print(n_grams(cleaned,4))

[['mary', ',', "n't", 'slap'], [',', "n't", 'slap', 'green'], ["n't", 'slap', 'green', 'witch'], ['slap', 'green', 'witch', '.']]


## 한국어 불용어

In [23]:
from nltk.tokenize import word_tokenize

example = "고기를 아무렇게나 구우려고 하면 안 돼. 고기라고 다 같은 게 아니거든. 예컨대 삼겹살을 구울 때는 중요한 게 있지."
stop_words = "아무거나 아무렇게나 어찌하든지 같다 비슷하다 예컨대 이럴정도로 하면 아니거든"

stop_words=set(stop_words.split(' '))
word_tokens=word_tokenize(example)

result=[word for word in word_tokens if not word in stop_words]

print(word_tokens)
print(result)

['고기를', '아무렇게나', '구우려고', '하면', '안', '돼', '.', '고기라고', '다', '같은', '게', '아니거든', '.', '예컨대', '삼겹살을', '구울', '때는', '중요한', '게', '있지', '.']
['고기를', '구우려고', '안', '돼', '.', '고기라고', '다', '같은', '게', '.', '삼겹살을', '구울', '때는', '중요한', '게', '있지', '.']


In [25]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

example = "NTLK는 한국어 불용어 데이터를 제공하지 않습니다. 왜냐하면 토큰화 단계에서 필요없는 조사, 접속사를 제거하면 되기 때문입니다."
stop_words = "않습니다 왜냐하면 되기"

word_tokens = word_tokenize(example)
stop_words=stop_words.split(' ')

result = []
for w in word_tokens:
    if w not in stop_words:
        result.append(w)
        
print(word_tokens, '\n')
print(result)

['NTLK는', '한국어', '불용어', '데이터를', '제공하지', '않습니다', '.', '왜냐하면', '토큰화', '단계에서', '필요없는', '조사', ',', '접속사를', '제거하면', '되기', '때문입니다', '.'] 

['NTLK는', '한국어', '불용어', '데이터를', '제공하지', '.', '토큰화', '단계에서', '필요없는', '조사', ',', '접속사를', '제거하면', '때문입니다', '.']


In [27]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

word = "불용어란 자주 등장하지만 데이터를 분석하는데 있어 큰 의미를 갖지 않는 단어들을 뜻합니다. 불용어는 임의로 설정할 수 도 있고, 영문의 불용어 리스트의 경우 NTLK 라이브러리에서 정의한 불용어 리스트를 사용할 수 있습니다. 다만 한국어의 경우 조사와 접속사의 사용이 다양하며, 언어의 변형이 많기 때문에 직접 정의하는게 좋습니다."

stop ="자주,종종,가끔,많이"

stop_list=stop.split(',')
tok=word_tokenize(word)

def stopword(word_tokenize):
    result=[]
    
    for w in word_tokenize:
        if w not in stop_list:
            result.append(w)
            
    return result

print('토큰화한 문장은'+str(tok)+'입니다.')
print('불용어를 제거하면'+str(stopword(tok))+'입니다.')

토큰화한 문장은['불용어란', '자주', '등장하지만', '데이터를', '분석하는데', '있어', '큰', '의미를', '갖지', '않는', '단어들을', '뜻합니다', '.', '불용어는', '임의로', '설정할', '수', '도', '있고', ',', '영문의', '불용어', '리스트의', '경우', 'NTLK', '라이브러리에서', '정의한', '불용어', '리스트를', '사용할', '수', '있습니다', '.', '다만', '한국어의', '경우', '조사와', '접속사의', '사용이', '다양하며', ',', '언어의', '변형이', '많기', '때문에', '직접', '정의하는게', '좋습니다', '.']입니다.
불용어를 제거하면['불용어란', '등장하지만', '데이터를', '분석하는데', '있어', '큰', '의미를', '갖지', '않는', '단어들을', '뜻합니다', '.', '불용어는', '임의로', '설정할', '수', '도', '있고', ',', '영문의', '불용어', '리스트의', '경우', 'NTLK', '라이브러리에서', '정의한', '불용어', '리스트를', '사용할', '수', '있습니다', '.', '다만', '한국어의', '경우', '조사와', '접속사의', '사용이', '다양하며', ',', '언어의', '변형이', '많기', '때문에', '직접', '정의하는게', '좋습니다', '.']입니다.


In [28]:
import spacy
nlp=spacy.load('en_core_web_sm')
doc=nlp(u"he was running late")

for token in doc:
    print('{} -> {}'.format(token, token.lemma_))

he -> he
was -> be
running -> run
late -> late


In [29]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

print(stemmer.stem('working'),stemmer.stem('works'),stemmer.stem('worked'))
print(stemmer.stem('amusing'),stemmer.stem('amuses'),stemmer.stem('amused'))
print(stemmer.stem('happier'),stemmer.stem('happiest'))
print(stemmer.stem('fancier'),stemmer.stem('fanciest'))
print(stemmer.stem('was'),stemmer.stem('love'))

work work work
amus amus amus
happier happiest
fancier fanciest
wa love


In [30]:
from nltk.stem import LancasterStemmer
stemmer=LancasterStemmer()

print(stemmer.stem('working'),stemmer.stem('works'),stemmer.stem('worked'))
print(stemmer.stem('amusing'),stemmer.stem('amuses'),stemmer.stem('amused'))
print(stemmer.stem('happier'),stemmer.stem('happiest'))
print(stemmer.stem('fancier'),stemmer.stem('fanciest'))
print(stemmer.stem('was'), stemmer.stem('love'))

work work work
amus amus amus
happy happiest
fant fanciest
was lov


In [31]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
stemmer=PorterStemmer()
text = "This was not the map we found in Billy Bones's chest, but an accurate copy, complete in all things--names and heights and soundings--with the single exception of the red crosses and the written notes."
words=word_tokenize(text)
print(words)

['This', 'was', 'not', 'the', 'map', 'we', 'found', 'in', 'Billy', 'Bones', "'s", 'chest', ',', 'but', 'an', 'accurate', 'copy', ',', 'complete', 'in', 'all', 'things', '--', 'names', 'and', 'heights', 'and', 'soundings', '--', 'with', 'the', 'single', 'exception', 'of', 'the', 'red', 'crosses', 'and', 'the', 'written', 'notes', '.']


In [32]:
print([stemmer.stem(w) for w in words])

['thi', 'wa', 'not', 'the', 'map', 'we', 'found', 'in', 'billi', 'bone', "'s", 'chest', ',', 'but', 'an', 'accur', 'copi', ',', 'complet', 'in', 'all', 'thing', '--', 'name', 'and', 'height', 'and', 'sound', '--', 'with', 'the', 'singl', 'except', 'of', 'the', 'red', 'cross', 'and', 'the', 'written', 'note', '.']


In [33]:
words=['formalize', 'allowance', 'electricical']
print(stemmer.stem(w) for w in words)

<generator object <genexpr> at 0x0000027771D160B0>


In [35]:
import nltk
nltk.download('punkt')
nltk.download('wordnet')

from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\a0109\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\a0109\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [36]:
def porter_stem(tokenize_list):
    p=PorterStemmer()
    result=[]
    
    for w in tokenize_list:
        result.append(p.stem(w))
        
    return result

def lancaster_stem(tokenize_list):
    l = LancasterStemmer()
    result=[]
    
    for w in tokenize_list:
        result.append(l.stem(w))
    return result

In [37]:
def compare(origin, compare):
    
    result=[]
    for i in range(len(origin)):
        if str(origin[i]) == str(compare[i]):
            pass
        else:
            result.append(compare[i])
    print('\033[1m'+str(result)+'\033[0w')

In [38]:
text = "The necrosis is closely related to the flow of blood. So we can make a diagnosis of tissue necrosis to observe the flow of blood."

word_tok=word_tokenize(text)

t1_p_stem=porter_stem(word_tok)
t1_l_stem=lancaster_stem(word_tok)

print("The result of using word_tokenize is this:")
print(word_tok)

print("there is porter algorithem stemming result below:")
print(t1_p_stem)

print("there is lancaster algorithem stemming result below:")
print(t1_l_stem)

print("there is the difference between porter and lancater below:")
compare(word_tok, t1_p_stem)
compare(word_tok, t1_l_stem)

The result of using word_tokenize is this:
['The', 'necrosis', 'is', 'closely', 'related', 'to', 'the', 'flow', 'of', 'blood', '.', 'So', 'we', 'can', 'make', 'a', 'diagnosis', 'of', 'tissue', 'necrosis', 'to', 'observe', 'the', 'flow', 'of', 'blood', '.']
there is porter algorithem stemming result below:
['the', 'necrosi', 'is', 'close', 'relat', 'to', 'the', 'flow', 'of', 'blood', '.', 'so', 'we', 'can', 'make', 'a', 'diagnosi', 'of', 'tissu', 'necrosi', 'to', 'observ', 'the', 'flow', 'of', 'blood', '.']
there is lancaster algorithem stemming result below:
['the', 'necros', 'is', 'clos', 'rel', 'to', 'the', 'flow', 'of', 'blood', '.', 'so', 'we', 'can', 'mak', 'a', 'diagnos', 'of', 'tissu', 'necros', 'to', 'observ', 'the', 'flow', 'of', 'blood', '.']
there is the difference between porter and lancater below:
['the', 'necrosi', 'close', 'relat', 'so', 'diagnosi', 'tissu', 'necrosi', 'observ']
['the', 'necros', 'clos', 'rel', 'so', 'mak', 'diagnos', 'tissu', 'necros', 'observ']


## RegexpStemmer class

In [39]:
from nltk.stem.regexp import RegexpStemmer
stemmer=RegexpStemmer('ing')
print(stemmer.stem('cooking'))
print(stemmer.stem('cookery'))
print(stemmer.stem('ingleside'))

cook
cookery
leside


In [40]:
from nltk.stem.snowball import SnowballStemmer
spanish_stemmer=SnowballStemmer('spanish')
print(spanish_stemmer.stem('hola'))

hol


In [42]:
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [43]:
text = "A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

In [44]:
# 문장 토큰화
text = sent_tokenize(text)
print(text)

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']


In [45]:
import nltk
nltk.download('stopwords')

#정제와 단어 토큰화
vocab = {} # 파이썬의 dictionary 자료형
sentences = []
stop_words = set(stopwords.words('english'))

for i in text:
    sentence = word_tokenize(i) # 단어 토큰화를 수행합니다.
    result = []

    for word in sentence: 
        word = word.lower() # 모든 단어를 소문자화하여 단어의 개수를 줄입니다.
        if word not in stop_words: # 단어 토큰화 된 결과에 대해서 불용어를 제거합니다.
            if len(word) > 2: # 단어 길이가 2이하인 경우에 대하여 추가로 단어를 제거합니다.
                result.append(word)
                if word not in vocab:
                    vocab[word] = 0 
                vocab[word] += 1
    sentences.append(result) 
print(sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\a0109\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [46]:
print(vocab)

{'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4, 'word': 2, 'keeping': 2, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1}


In [47]:
print(vocab["barber"]) # 'barber'라는 단어의 빈도수 출력

8


In [61]:
#빈도수가 높은 순서대로 정렬
vocab_sorted = sorted(vocab.items(), key = lambda x:x[1], reverse = True)
print(vocab_sorted)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3), ('word', 2), ('keeping', 2), ('good', 1), ('knew', 1), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)]


In [75]:
word_to_index={}
i=0
for (word,frequency) in vocab_sorted:
    if frequency>1:
        i=i+1
        word_to_index[word]=i
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


In [78]:
vocab_size=6
words_frequency=[w for w,c in word_to_index.items() if c>=vocab_size+1]
for w in words_frequency:
    del word_to_index[w]
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6}


In [53]:
word_to_index['OOV']=len(word_to_index)+1

In [54]:
encoded=[]
for s in sentences:
    temp=[]
    for w in s:
        try:
            temp.append(word_to_index[w])
        except KeyError:
            temp.append(word_to_index['OOV'])
    encoded.append(temp)
print(encoded)

[[1, 5], [1, 6, 5], [1, 3, 5], [6, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [6, 6, 3, 2, 6, 1, 6], [1, 6, 3, 6]]


In [80]:
import numpy as np

In [94]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [95]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

In [96]:
np.concatenate((a,b), axis=0)

array([1, 2, 3, 4, 5, 6])

In [97]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
np.concatenate((a,b),axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [102]:
a,b

(array([1, 2, 3]), array([4, 5, 6]))

In [103]:
np.column_stack([a,b])

array([[1, 4],
       [2, 5],
       [3, 6]])

## Counter

In [108]:
from collections import Counter

In [109]:
print(sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [110]:
words=sum(sentences,[])
print(words)

['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge', 'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret', 'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept', 'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge', 'mountain']


In [111]:
vocab=Counter(words)
print(vocab)

Counter({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1})


In [112]:
print(vocab["barber"])

8


In [113]:
vocab_size=5
vocab=vocab.most_common(vocab_size)
vocab

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [114]:
word_to_index={}
i=0
for (word, frequency) in vocab:
    i = i+1
    word_to_index[word]=i
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


## zip

In [115]:
sequences=[['a',1],['b',2],['c',3]] # 리스트의 리스트 또는 행렬 또는 2d 텐서
X,y=zip(*sequences) #*:iterables ->args(list) ->
print(X)
print(y)

('a', 'b', 'c')
(1, 2, 3)


In [116]:
X,y=zip(['a',1],['b',2],['c',3])
print(X,y)

('a', 'b', 'c') (1, 2, 3)


## Pandas 데이터 프레임 이용

In [118]:
import pandas as pd
values=[['당신에게 드리는 마지막 혜택!',1],
       ['내일 뵐 수 있을지 확인 부탁드립...',0],
       ['도연씨. 잘 지내시죠? 오랜만입...',0],
       ['(광고)AI로 주가를 예측할 수 있다!',1]]
columns=['메일 본문', '스팸 메일 유무']

df=pd.DataFrame(values,columns=columns)
X=df['메일 본문']
y=df['스팸 메일 유무']
print(X)
print(y)

0         당신에게 드리는 마지막 혜택!
1    내일 뵐 수 있을지 확인 부탁드립...
2     도연씨. 잘 지내시죠? 오랜만입...
3    (광고)AI로 주가를 예측할 수 있다!
Name: 메일 본문, dtype: object
0    1
1    0
2    0
3    1
Name: 스팸 메일 유무, dtype: int64


## NLTK의 FreqDist 사용하기

In [120]:
from nltk import FreqDist
import numpy as np

In [121]:
vocab=FreqDist(np.hstack(sentences))
vocab

FreqDist({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, ...})

In [122]:
print(vocab["barber"])

8


In [123]:
vocab_size=5
vocab=vocab.most_common(vocab_size)
vocab

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [124]:
word_to_index={word[0]: index+1 for index, word in enumerate(vocab)}
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}
